=== ATHIRACM2003/WEB_LAB_4_AND_5/WS_LAB_5/travel5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="www.abc.com/trav"
           xmlns="www.abc.com/trav"
           elementFormDefault="qualified">

  <!-- Root element -->
  <xs:element name="travel">
    <xs:complexType>
      <xs:sequence>
        <!-- Location element -->
        <xs:element name="loc" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <!-- Destination element -->
              <xs:element name="destination">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="city" type="xs:string"/>
                    <xs:element name="country" type="countryType"/>
                    <xs:element name="hotel" type="xs:string"/>
                    <xs:element name="hotel_rent" type="xs:decimal"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
              <!-- Flight element -->
              <xs:element name="flight">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="airline" type="xs:string"/>
                    <xs:element name="departure" type="xs:date"/>
                    <xs:element name="arrival" type="xs:date"/>
                    <xs:element name="amount" type="xs:decimal"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:ID" use="required"/>
                </xs:complexType>
              </xs:element>
              <!-- Bus element -->
              <xs:element name="bus">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="boarding" type="xs:string"/>
                    <xs:element name="departure" type="xs:date"/>
                    <xs:element name="arrival" type="xs:date"/>
                    <xs:element name="amount" type="xs:decimal"/>
                    <xs:element name="dropping" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:ID" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- Hotels element -->
        <xs:element name="hotels">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hotel">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="stars">
                      <xs:simpleType>
                        <xs:restriction base="xs:int">
                          <xs:minInclusive value="0"/>
                          <xs:maxInclusive value="5"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="price" type="xs:decimal"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="countryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="USA"/>
      <xs:enumeration value="India"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ATHIRACM2003/WEB_LAB_4_AND_5/WS_LAB_5/travel5.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="transform.xsl" type="text/xsl"?>
<?xml-model href="travel5.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<travel xmlns:ns="http://abc.com/trav" xsi:schemaLocation="www.abc.com/trav travel5.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
  <loc>
    <destination id="1">
      <city>New York</city>
      <country>USA</country>
      <hotel>Vigaza</hotel>
      <hotel_rent>18000</hotel_rent>
    </destination>
    <flight id="f1">
      <airline>Delta</airline>
      <departure>2024-10-24</departure>
      <arrival>2024-10-25</arrival>
      <amount>5000</amount>
    </flight>
    <bus id="b1">
      <boarding>Pune</boarding>
      <departure>2025-01-10</departure>
      <arrival>2025-01-11</arrival>
      <amount>2000</amount>
      <dropping>Punjab</dropping>
  </bus>
  </loc>
<loc>
  <destination id="2">
    <city>Paris</city>
    <country>France</country>
    <hotel>Shuanza</hotel>
      <hotel_rent>16500</hotel_rent>
  </destination>
  <flight id="f2">
    <airline>Delta</airline>
    <departure>2024-12-25</departure>
    <arrival>2024-12-26</arrival>
    <amount>5000</amount>
  </flight>
    <bus id="b2">
        <boarding>Pune</boarding>
        <departure>2025-01-25</departure>
        <arrival>2025-01-28</arrival>
        <amount>1000</amount>
        <dropping>Shmla</dropping>
    </bus>
  </loc>
<hotels>
  <hotel id="h2">
    <name>Taj Hotel</name>
    <stars>5</stars>
    <price>1500</price>
  </hotel>
  </hotels>
<hotels>
  <hotel id="h1">
    <name>Grand Central Hotel</name>
    <stars>4</stars>
    <price>1000</price>
  </hotel>
</hotels>
<hotels>
    <hotel id="h3">
      <name>May Hotel</name>
      <stars>3</stars>
      <price>800</price>
    </hotel>
  </hotels>
  </travel>
